"""ApiClient — a machine-client credential for server-to-server
integration (milestone item 10). This is the minimum secure foundation
the milestone asks for, not a full OAuth2 authorization server: one
long-lived, scoped, revocable, organization-associated credential per
external system integration (a "service account"), verified via a
`client_id` + secret bearer credential on every request — see
`app/api/deps_machine_auth.py`.

**Never a raw API secret at rest.** `hashed_secret` stores
`hashlib.sha256(secret)` (see `app/services/api_client_service.py` for
why sha256 alone, not a slow password-hashing KDF like bcrypt/scrypt, is
the appropriate choice here: the secret is a long, high-entropy
`secrets.token_urlsafe()` value generated by SIE itself, not a
human-chosen low-entropy password — the threat sha256 is weak against
(fast brute-force of a *guessable* secret) does not apply). The raw
secret is returned to the caller exactly once, at creation/rotation time,
and is never stored, logged, or returned again — `secret_prefix` (the
first few characters of the raw secret) is kept only so a client can be
identified in a UI/support conversation without exposing the whole
value, the same "show the last 4 digits" pattern used for payment cards
and API-key management UIs elsewhere.

**Scopes, not the full permission-inheritance-from-membership model.**
`OrganizationMembership`/`TenantContext` (see app/services/tenant_context.py)
model a *human* user's role-derived permissions. A machine client has no
role — it is granted an explicit, minimal `scopes` list (values from
`app.services.permissions.Permission`) at creation time, and never more
than that, regardless of what any human's role in the organization would
grant. This is deliberately a narrower, simpler model than
`TenantContext`'s.
"""

from datetime import datetime

from sqlalchemy import JSON as GenericJSON
from sqlalchemy import DateTime, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, OrganizationScopedMixin, TimestampMixin, UUIDPrimaryKeyMixin

_JSONType = GenericJSON().with_variant(JSONB(), "postgresql")


class ApiClient(UUIDPrimaryKeyMixin, OrganizationScopedMixin, TimestampMixin, Base):
    __tablename__ = "api_clients"

    name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Public identifier, safe to log/display -- distinct from the secret.
    client_id: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)
    hashed_secret: Mapped[str] = mapped_column(String(128), nullable=False)
    secret_prefix: Mapped[str] = mapped_column(String(12), nullable=False)

    # app.services.permissions.Permission values, e.g.
    # ["safety_data:write", "safety_data:read"] -- see module docstring.
    scopes: Mapped[list[str]] = mapped_column(_JSONType, nullable=False, default=list)

    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACTIVE")  # ACTIVE | REVOKED

    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rotated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Optional (Intelligence Platform Integration v0.1, item 25's "expiration
    # where appropriate") -- NULL means "does not expire", never a magic
    # sentinel date. `ApiClientService.authenticate()` treats a client whose
    # `expires_at` has passed exactly like a revoked one (rejected, not a
    # partial/soft-expired state) but leaves `status` and `revoked_at`
    # alone -- expiry and revocation are recorded as two distinct, honest
    # reasons a credential stopped working, not conflated into one field.
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    organization: Mapped["Organization"] = relationship()  # noqa: F821

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<ApiClient id={self.id!s} organization_id={self.organization_id!s} "
            f"client_id={self.client_id!r} status={self.status!r}>"
        )
