"""RAGService — the RAG orchestration layer (milestone item 4).

    User question
        -> (already-authorized tenant context — see app/api/v1/rag.py;
            this service never authorizes anything itself)
        -> RetrievalService.search()            [existing, reused, unmodified]
        -> EvidenceSelectionService.select()     [app/rag/evidence_selection.py]
        -> evaluate_sufficiency()                [app/rag/sufficiency.py]
        -> detect_conflicts()                    [app/rag/conflict.py]
        -> [deterministic gate -- see below]
        -> build_grounded_context()              [app/rag/context_builder.py]
        -> LLMProvider.generate()                [app/llm/provider.py]
        -> validate_and_sanitize_citations()      [app/rag/citations.py]
        -> RAGResponse                            [app/rag/results.py]

**This service does not query PostgreSQL vectors directly and never
duplicates retrieval logic** — it calls the existing
`app.retrieval.retrieval_service.retrieval_service.search()` exactly as
`app/api/v1/retrieval.py` does, with the same already-authorized
`allowed_organization_id` contract (see that service's own docstring for
the tenant isolation guarantee this inherits unchanged).

**The deterministic gate — every reason an LLM is never even called:**

  1. `evidence_state == INSUFFICIENT` -> abstain. Never delegated to the
     LLM (milestone item 6/7) — see `app/rag/sufficiency.py`.
  2. A source conflict is detected among the selected evidence -> return
     a `SOURCE_CONFLICT` response built directly from the conflicting
     evidence, not generated by the LLM. The milestone is explicit that
     "the model must not silently select one" side of a conflict — the
     surest way to guarantee that is to never ask it to resolve one at
     all (milestone item 15/36).
  3. The configured `LLMProvider.is_external` is `True`, selected evidence
     includes organization-private content, and
     `settings.ALLOW_EXTERNAL_LLM_FOR_PRIVATE_DATA` is `False` -> refuse
     with a `PRIVACY_BLOCKED` outcome rather than silently transmitting
     private content externally (milestone item 39).

Only once none of those apply is `LLMProvider.generate()` actually called.
Its output is still never trusted blindly: every `[E#]` citation is
validated against the evidence that was actually supplied
(`app/rag/citations.py`), and an answer that cites *none* of the supplied
evidence — even though evidence was available — is rejected rather than
returned (`UNSUPPORTED_CLAIM_REJECTED`, milestone item 32) rather than
exposed as if it were grounded.

**Audit/observability (milestone items 23-24).** Reuses the existing
`app.services.audit_service.AuditService` — no new database table. See
that call site below for exactly why a dedicated table was judged
unnecessary for this milestone: `AuditLog.event_metadata` already gives a
tenant-scoped, indexed, JSON-capable place for RAG request/reproducibility
metadata, and reusing it keeps this milestone from adding schema surface
that "genuinely necessary" (milestone item 45) does not require. The raw
query text and generated answer are included in that metadata only when
`settings.LOG_RAG_QUERY_TEXT`/`LOG_RAG_ANSWER_TEXT` are explicitly enabled
(both default `False`) — identical to `RetrievalService`'s own
`LOG_RETRIEVAL_QUERY_TEXT` precedent.
"""

from __future__ import annotations

import logging
import time
import uuid

from sqlalchemy.orm import Session

from app.core.config import settings
from app.embeddings.provider import EmbeddingProvider
from app.llm.provider import (
    LLMGenerationConfig,
    LLMProvider,
    LLMProviderError,
    LLMRequest,
    get_llm_provider,
)
from app.rag.citations import validate_and_sanitize_citations
from app.rag.conflict import detect_conflicts
from app.rag.context_builder import build_grounded_context
from app.rag.evidence_selection import EvidenceSelectionService, evidence_selection_service
from app.rag.prompt import get_system_prompt
from app.rag.results import (
    Citation,
    EvidenceState,
    RAGOutcome,
    RAGResponse,
    SelectedEvidenceItem,
    SourceConflict,
)
from app.rag.sufficiency import evaluate_sufficiency
from app.retrieval.filters import RetrievalFilters
from app.retrieval.retrieval_service import retrieval_service
from app.services.audit_service import AuditAction, audit_service

logger = logging.getLogger(__name__)


class RAGService:
    def query(
        self,
        db: Session,
        *,
        query_text: str,
        allowed_organization_id: uuid.UUID | None,
        user_id: uuid.UUID | None = None,
        filters: RetrievalFilters | None = None,
        top_k: int | None = None,
        embedding_provider: EmbeddingProvider | None = None,
        llm_provider: LLMProvider | None = None,
        generation_config: LLMGenerationConfig | None = None,
        evidence_selection: EvidenceSelectionService = evidence_selection_service,
    ) -> RAGResponse:
        started = time.monotonic()
        llm_provider = llm_provider or get_llm_provider()
        generation_config = generation_config or LLMGenerationConfig(
            temperature=settings.LLM_TEMPERATURE,
            max_output_tokens=settings.LLM_MAX_OUTPUT_TOKENS,
            timeout_seconds=settings.LLM_TIMEOUT_SECONDS,
        )
        prompt_version, system_instructions = get_system_prompt()

        retrieval_started = time.monotonic()
        retrieval_response = retrieval_service.search(
            db,
            query_text=query_text,
            allowed_organization_id=allowed_organization_id,
            filters=filters,
            top_k=top_k,
            provider=embedding_provider,
        )
        retrieval_duration_ms = round((time.monotonic() - retrieval_started) * 1000, 2)

        selection = evidence_selection.select(retrieval_response.results)
        evidence_state = evaluate_sufficiency(selection.selected)
        conflicts = detect_conflicts(selection.selected) if len(selection.selected) >= 2 else []

        retrieval_metadata = {
            "retrieved_count": selection.retrieved_count,
            "selected_count": selection.selected_count,
            "excluded_insufficient_quality_count": selection.excluded_insufficient_quality_count,
            "excluded_low_relevance_count": selection.excluded_low_relevance_count,
            "excluded_duplicate_count": selection.excluded_duplicate_count,
            "excluded_over_limit_count": selection.excluded_over_limit_count,
            "retrieval_outcome": retrieval_response.outcome.value,
            "retrieval_duration_ms": retrieval_duration_ms,
            "filters_applied": retrieval_response.filters_applied,
            "embedding_model": {
                "provider": retrieval_response.embedding_provider,
                "model_name": retrieval_response.embedding_model,
                "model_version": retrieval_response.embedding_model_version,
            },
        }
        reproducibility = {
            "query": query_text,
            "retrieval_filters": retrieval_response.filters_applied,
            "prompt_version": prompt_version,
            "embedding_model": retrieval_metadata["embedding_model"],
            "evidence": [
                {
                    "citation_id": item.citation_id,
                    "chunk_id": str(item.result.chunk_id),
                    "document_version_id": str(item.result.document_version_id),
                    "similarity": item.result.similarity,
                    "relevance": item.result.relevance.value,
                }
                for item in selection.selected
            ],
        }

        llm_duration_ms: float | None = None
        invalid_citation_count = 0

        if evidence_state == EvidenceState.INSUFFICIENT:
            response = self._insufficient_evidence_response(
                query_text, evidence_state, selection, retrieval_metadata, reproducibility, prompt_version
            )
        elif conflicts:
            response = self._conflict_response(
                query_text, evidence_state, selection, conflicts, retrieval_metadata, reproducibility, prompt_version
            )
        else:
            privacy_block_reason = self._privacy_block_reason(selection.selected, llm_provider)
            if privacy_block_reason is not None:
                response = self._privacy_blocked_response(
                    query_text,
                    evidence_state,
                    selection,
                    retrieval_metadata,
                    reproducibility,
                    prompt_version,
                    privacy_block_reason,
                )
            else:
                grounded_context = build_grounded_context(selection.selected)
                llm_request = LLMRequest(
                    system_instructions=system_instructions,
                    grounded_context=grounded_context,
                    user_question=query_text,
                    config=generation_config,
                )
                llm_started = time.monotonic()
                try:
                    llm_response = llm_provider.generate(llm_request)
                except LLMProviderError as exc:
                    llm_duration_ms = round((time.monotonic() - llm_started) * 1000, 2)
                    logger.warning(
                        "rag_llm_provider_failure",
                        extra={"provider": llm_provider.provider_name, "error": str(exc)},
                    )
                    response = self._provider_failure_response(
                        query_text,
                        evidence_state,
                        selection,
                        retrieval_metadata,
                        reproducibility,
                        prompt_version,
                        llm_provider,
                    )
                else:
                    llm_duration_ms = round((time.monotonic() - llm_started) * 1000, 2)
                    response, invalid_citation_count = self._answered_response(
                        query_text,
                        evidence_state,
                        selection,
                        llm_response,
                        retrieval_metadata,
                        reproducibility,
                        prompt_version,
                    )

        retrieval_metadata["llm_duration_ms"] = llm_duration_ms
        total_duration_ms = round((time.monotonic() - started) * 1000, 2)
        retrieval_metadata["total_duration_ms"] = total_duration_ms

        self._audit(
            db,
            query_text=query_text,
            allowed_organization_id=allowed_organization_id,
            user_id=user_id,
            response=response,
            llm_provider=llm_provider,
            retrieval_duration_ms=retrieval_duration_ms,
            llm_duration_ms=llm_duration_ms,
            total_duration_ms=total_duration_ms,
        )
        self._log(
            query_text=query_text,
            response=response,
            retrieval_duration_ms=retrieval_duration_ms,
            llm_duration_ms=llm_duration_ms,
            total_duration_ms=total_duration_ms,
            invalid_citation_count=invalid_citation_count,
        )
        return response

    # --- Deterministic, no-LLM response builders --------------------------

    def _insufficient_evidence_response(
        self, query_text, evidence_state, selection, retrieval_metadata, reproducibility, prompt_version
    ) -> RAGResponse:
        reason = (
            f"SIE searched its knowledge base for '{query_text}' and found "
            f"{selection.retrieved_count} candidate result(s), of which "
            f"{selection.selected_count} met the relevance/quality bar required to use as "
            "evidence. That is not enough to answer this question. SIE does not have "
            "sufficient supporting evidence. Consider rephrasing the question, narrowing "
            "or widening its scope, or confirming that relevant knowledge has been "
            "ingested for this organization."
        )
        return RAGResponse(
            query=query_text,
            outcome=RAGOutcome.INSUFFICIENT_EVIDENCE,
            evidence_state=evidence_state,
            answer=None,
            citations=[],
            conflicts=[],
            evidence_count=selection.selected_count,
            warnings=[],
            abstention_reason=reason,
            retrieval_metadata=retrieval_metadata,
            model_metadata=None,
            prompt_version=prompt_version,
            reproducibility=reproducibility,
        )

    def _conflict_response(
        self,
        query_text,
        evidence_state,
        selection,
        conflicts: list[SourceConflict],
        retrieval_metadata,
        reproducibility,
        prompt_version,
    ) -> RAGResponse:
        involved_ids = {c.citation_id_a for c in conflicts} | {c.citation_id_b for c in conflicts}
        citations = [
            self._to_citation(item) for item in selection.selected if item.citation_id in involved_ids
        ]
        lines = [
            "SIE found conflicting evidence for this question and cannot resolve the "
            "conflict automatically:"
        ]
        for c in conflicts:
            lines.append(
                f'- [{c.citation_id_a}] ({c.source_name_a}, version {c.version_label_a}'
                f'{", effective " + c.effective_date_a if c.effective_date_a else ""}) '
                f'states: "{c.statement_a}"'
            )
            lines.append(
                f'- [{c.citation_id_b}] ({c.source_name_b}, version {c.version_label_b}'
                f'{", effective " + c.effective_date_b if c.effective_date_b else ""}) '
                f'states: "{c.statement_b}"'
            )
        lines.append(
            "Both sources are identified above. SIE cannot resolve this conflict without "
            "additional authority/context, and does not choose one source over the other "
            "automatically."
        )
        return RAGResponse(
            query=query_text,
            outcome=RAGOutcome.SOURCE_CONFLICT,
            evidence_state=evidence_state,
            answer="\n".join(lines),
            citations=citations,
            conflicts=conflicts,
            evidence_count=selection.selected_count,
            warnings=["SOURCE_CONFLICT: conflicting evidence was found; see `conflicts`."],
            abstention_reason="Conflicting evidence prevents a single confident answer.",
            retrieval_metadata=retrieval_metadata,
            model_metadata=None,
            prompt_version=prompt_version,
            reproducibility=reproducibility,
        )

    def _privacy_block_reason(
        self, selected: list[SelectedEvidenceItem], llm_provider: LLMProvider
    ) -> str | None:
        if not llm_provider.is_external or settings.ALLOW_EXTERNAL_LLM_FOR_PRIVATE_DATA:
            return None
        has_private_evidence = any(item.result.organization_id is not None for item in selected)
        if not has_private_evidence:
            return None
        return (
            f"The configured LLM provider ({llm_provider.provider_name}) sends its input "
            "to an external service, ALLOW_EXTERNAL_LLM_FOR_PRIVATE_DATA is disabled, and "
            "the evidence selected to answer this question includes organization-private "
            "content. SIE will not transmit private content to an external provider "
            "without that being explicitly enabled."
        )

    def _privacy_blocked_response(
        self, query_text, evidence_state, selection, retrieval_metadata, reproducibility, prompt_version, reason
    ) -> RAGResponse:
        return RAGResponse(
            query=query_text,
            outcome=RAGOutcome.PRIVACY_BLOCKED,
            evidence_state=evidence_state,
            answer=None,
            citations=[],
            conflicts=[],
            evidence_count=selection.selected_count,
            warnings=["PRIVACY_BLOCKED: external LLM provider blocked from private evidence."],
            abstention_reason=reason,
            retrieval_metadata=retrieval_metadata,
            model_metadata=None,
            prompt_version=prompt_version,
            reproducibility=reproducibility,
        )

    def _provider_failure_response(
        self, query_text, evidence_state, selection, retrieval_metadata, reproducibility, prompt_version, llm_provider
    ) -> RAGResponse:
        return RAGResponse(
            query=query_text,
            outcome=RAGOutcome.PROVIDER_FAILURE,
            evidence_state=evidence_state,
            answer=None,
            citations=[],
            conflicts=[],
            evidence_count=selection.selected_count,
            warnings=["PROVIDER_FAILURE: the LLM provider failed; no answer was generated."],
            abstention_reason=(
                "The language model provider failed while generating a response. No "
                "answer was fabricated. The retrieved evidence for this query is unaffected "
                "and remains available via `reproducibility`."
            ),
            retrieval_metadata=retrieval_metadata,
            model_metadata={"provider": llm_provider.provider_name, "model": llm_provider.model_name},
            prompt_version=prompt_version,
            reproducibility=reproducibility,
        )

    def _answered_response(
        self, query_text, evidence_state, selection, llm_response, retrieval_metadata, reproducibility, prompt_version
    ) -> tuple[RAGResponse, int]:
        valid_ids = {item.citation_id for item in selection.selected}
        sanitized_text, valid_used, invalid_found = validate_and_sanitize_citations(
            llm_response.text, valid_ids
        )

        warnings: list[str] = []
        for invalid_id in invalid_found:
            warnings.append(
                f"INVALID_CITATION_REMOVED: {invalid_id} was not among the evidence "
                "supplied to the model and was removed from the response."
            )

        usage = llm_response.usage
        model_metadata = {
            "provider": llm_response.provider,
            "model": llm_response.model,
            "model_version": llm_response.model_version,
            "usage": {
                "prompt_tokens": usage.prompt_tokens,
                "completion_tokens": usage.completion_tokens,
                "total_tokens": usage.total_tokens,
            }
            if usage
            else None,
            "request_id": llm_response.request_id,
        }

        if not valid_used:
            # Unsupported-claim guardrail (milestone item 32): evidence
            # was available and supplied, but the generated answer cited
            # none of it. An uncited claim from a "grounded" pipeline is
            # exactly the failure mode this milestone forbids -- reject
            # it rather than expose it as if it were grounded.
            warnings.append(
                "UNSUPPORTED_CLAIM_REJECTED: the generated answer did not cite any of "
                "the supplied evidence and was rejected rather than returned."
            )
            return (
                RAGResponse(
                    query=query_text,
                    outcome=RAGOutcome.UNSUPPORTED_CLAIM_REJECTED,
                    evidence_state=evidence_state,
                    answer=None,
                    citations=[],
                    conflicts=[],
                    evidence_count=selection.selected_count,
                    warnings=warnings,
                    abstention_reason=(
                        "SIE could not verify the generated answer against the retrieved "
                        "evidence (no citations were present) and withheld it rather than "
                        "presenting an unsupported claim."
                    ),
                    retrieval_metadata=retrieval_metadata,
                    model_metadata=model_metadata,
                    prompt_version=prompt_version,
                    reproducibility=reproducibility,
                ),
                len(invalid_found),
            )

        if evidence_state == EvidenceState.PARTIAL:
            warnings.append(
                "PARTIAL_EVIDENCE: only partial supporting evidence was found for this "
                "question -- the answer may not cover every aspect of what was asked. "
                "See `evidence_state`."
            )

        citations = [item for item in selection.selected if item.citation_id in valid_used]
        return (
            RAGResponse(
                query=query_text,
                outcome=RAGOutcome.ANSWERED,
                evidence_state=evidence_state,
                answer=sanitized_text,
                citations=[self._to_citation(item) for item in citations],
                conflicts=[],
                evidence_count=selection.selected_count,
                warnings=warnings,
                abstention_reason=None,
                retrieval_metadata=retrieval_metadata,
                model_metadata=model_metadata,
                prompt_version=prompt_version,
                reproducibility=reproducibility,
            ),
            len(invalid_found),
        )

    def _to_citation(self, item: SelectedEvidenceItem) -> Citation:
        r = item.result
        return Citation(
            citation_id=item.citation_id,
            chunk_id=r.chunk_id,
            document_id=r.document_id,
            document_version_id=r.document_version_id,
            source_id=r.source_id,
            source_name=r.source_name,
            document_title=r.document_title,
            version_label=r.version_label,
            location=r.location,
            content_type=r.content_type,
            verification_status=r.verification_status,
            extraction_quality=r.extraction_quality,
            source_authority_level=r.source_authority_level,
            similarity=r.similarity,
            scope=r.scope,
            organization_id=r.organization_id,
        )

    # --- Audit / observability ---------------------------------------------

    def _audit(
        self,
        db: Session,
        *,
        query_text: str,
        allowed_organization_id: uuid.UUID | None,
        user_id: uuid.UUID | None,
        response: RAGResponse,
        llm_provider: LLMProvider,
        retrieval_duration_ms: float,
        llm_duration_ms: float | None,
        total_duration_ms: float,
    ) -> None:
        # Reuses the existing AuditService/AuditLog -- see this module's
        # own docstring for why no new database table was added for this
        # milestone. Never the raw query/answer text unless explicitly
        # enabled (LOG_RAG_QUERY_TEXT / LOG_RAG_ANSWER_TEXT, both off by
        # default) -- everything else here is shape/metadata, safe to
        # retain indefinitely under the existing audit-log retention.
        audit_service.log(
            db,
            action=AuditAction.RAG_QUERY_EXECUTED,
            resource_type="RAGRequest",
            organization_id=allowed_organization_id,
            user_id=user_id,
            metadata={
                "outcome": response.outcome.value,
                "evidence_state": response.evidence_state.value,
                "evidence_count": response.evidence_count,
                "citation_count": len(response.citations),
                "conflict_count": len(response.conflicts),
                "warning_count": len(response.warnings),
                "prompt_version": response.prompt_version,
                "llm_provider": llm_provider.provider_name,
                "llm_model": llm_provider.model_name,
                "llm_model_version": llm_provider.model_version,
                "retrieval_duration_ms": retrieval_duration_ms,
                "llm_duration_ms": llm_duration_ms,
                "total_duration_ms": total_duration_ms,
                "success": response.outcome
                in (RAGOutcome.ANSWERED, RAGOutcome.INSUFFICIENT_EVIDENCE, RAGOutcome.SOURCE_CONFLICT),
                # Reproducibility (milestone items 25-26): enough to
                # identify exactly what evidence and model configuration
                # produced this response, without the full prompt/answer.
                "reproducibility": response.reproducibility,
                "query_length": len(query_text),
                "query_text": query_text if settings.LOG_RAG_QUERY_TEXT else None,
                "answer_text": (
                    response.answer if settings.LOG_RAG_ANSWER_TEXT and response.answer else None
                ),
            },
        )

    def _log(
        self,
        *,
        query_text: str,
        response: RAGResponse,
        retrieval_duration_ms: float,
        llm_duration_ms: float | None,
        total_duration_ms: float,
        invalid_citation_count: int,
    ) -> None:
        logger.info(
            "rag_query",
            extra={
                "outcome": response.outcome.value,
                "evidence_state": response.evidence_state.value,
                "evidence_count": response.evidence_count,
                "citation_count": len(response.citations),
                "invalid_citation_count": invalid_citation_count,
                "warning_count": len(response.warnings),
                "retrieval_duration_ms": retrieval_duration_ms,
                "llm_duration_ms": llm_duration_ms,
                "total_duration_ms": total_duration_ms,
                "query_length": len(query_text),
                "query_text": query_text if settings.LOG_RAG_QUERY_TEXT else None,
            },
        )


rag_service = RAGService()
