"""universal ingestion engine

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-31 17:47:02.922359

Adds the two tables for the Universal Knowledge & Data Ingestion Engine
v0.1: `ingested_files` (file metadata — what a file is and its current
processing state) and `ingestion_jobs` (one immutable record per attempt
to ingest a file), mirroring the KnowledgeDocument/
KnowledgeDocumentVersion current-state/history split already used
elsewhere in this schema. No changes to any existing table — purely
additive, unlike 0003.

Both tables' `ingestion_status`/`status` columns are typed
`sa.Enum(IngestionJobStatus, name="ingestion_job_status")` — the same
enum type, referenced twice, not two separate types. PostgreSQL only
creates the named type once regardless of how many columns reference it;
this migration relies on that (not on issuing `CREATE TYPE` twice), which
is why it works but wouldn't if `ingested_files` were, say, in a
different migration than `ingestion_jobs` without special handling.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_files',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('detected_media_type', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=1000), nullable=False),
    sa.Column('ingestion_status', sa.Enum('RECEIVED', 'VALIDATING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='ingestion_job_status'), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'SUCCEEDED', 'PARTIAL', 'FAILED', name='extraction_status'), nullable=False),
    sa.Column('extraction_method', sa.Enum('TEXT_EXTRACTION', 'STRUCTURED_PARSE', 'OCR', 'NONE', name='extraction_method'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingested_files_content_hash', 'ingested_files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ingested_files_organization_id'), 'ingested_files', ['organization_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='ingestion_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['ingested_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_document_id'), 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_file_id'), 'ingestion_jobs', ['file_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_organization_id'), 'ingestion_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_organization_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_file_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_document_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_ingested_files_organization_id'), table_name='ingested_files')
    op.drop_index('ix_ingested_files_content_hash', table_name='ingested_files')
    op.drop_table('ingested_files')

    # Native enum types created by the sa.Enum columns above are not
    # dropped automatically by op.drop_table() on PostgreSQL; drop them
    # explicitly for a clean downgrade (see migrations 0002/0003 for the
    # same pattern).
    sa.Enum(name='extraction_method').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='extraction_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ingestion_job_status').drop(op.get_bind(), checkfirst=True)
