"""intelligence and predictive analytics foundation

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-01 05:44:56.533999

SIE Intelligence & Predictive Analytics Foundation v0.1. Additive only —
no existing table or column is altered or dropped. Adds two new tables:

  * `safety_events` — the canonical, cross-domain organizational safety
    event representation (see app/models/safety_event.py's own docstring
    for why this is one table, not one per data domain, and why
    `event_type`/`event_subtype`/`severity`/`status`/`data_quality_status`
    are plain indexed `String` columns rather than native PostgreSQL enum
    columns — deliberately avoiding a repeat of migration 0005's
    enum-type-creation defect for a vocabulary that is expected to grow
    without a migration).
  * `api_clients` — machine-client credentials for server-to-server
    integration (see app/models/api_client.py's own docstring). Never
    stores a raw secret — only a sha256 hash and a short, safe-to-display
    prefix.

Autogenerated via `alembic revision --autogenerate` against this
project's own models, then hand-reviewed: one unrelated, pre-existing
drift this autogenerate run also detected (a `DROP INDEX`/`CREATE INDEX`
pair for `ix_knowledge_chunk_embeddings_model_identity`, a column
combination declared in migration 0006 but not mirrored as an explicit
`Index(...)` on `app/models/embedding.py`) was deliberately removed from
this migration — it predates this milestone, is unrelated to it, and
this migration stays purely additive per the same discipline every prior
migration in this project follows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('api_clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('hashed_secret', sa.String(length=128), nullable=False),
    sa.Column('secret_prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_clients_client_id'), 'api_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_api_clients_organization_id'), 'api_clients', ['organization_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_subtype', sa.String(length=100), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('potential_severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_content_hash', sa.String(length=128), nullable=False),
    sa.Column('normalization_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('ingestion_batch_id', sa.Uuid(), nullable=False),
    sa.Column('data_quality_status', sa.String(length=20), nullable=False),
    sa.Column('data_quality_issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'source_record_id', name='uq_safety_events_org_source_record')
    )
    op.create_index(op.f('ix_safety_events_data_quality_status'), 'safety_events', ['data_quality_status'], unique=False)
    op.create_index(op.f('ix_safety_events_event_time'), 'safety_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_safety_events_event_type'), 'safety_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_safety_events_ingestion_batch_id'), 'safety_events', ['ingestion_batch_id'], unique=False)
    op.create_index(op.f('ix_safety_events_ingestion_time'), 'safety_events', ['ingestion_time'], unique=False)
    op.create_index(op.f('ix_safety_events_organization_id'), 'safety_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_safety_events_site_id'), 'safety_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_safety_events_source_system'), 'safety_events', ['source_system'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_safety_events_source_system'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_site_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_organization_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_ingestion_time'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_ingestion_batch_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_event_type'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_event_time'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_data_quality_status'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_api_clients_organization_id'), table_name='api_clients')
    op.drop_index(op.f('ix_api_clients_client_id'), table_name='api_clients')
    op.drop_table('api_clients')
