"""predictive risk modeling foundation

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-01 06:41:14.781885

SIE Predictive Risk Modeling Specification v0.1. Additive only — no
existing table or column is altered or dropped. Adds three new tables:

  * `feature_snapshots` — an immutable record of exactly what the
    feature-engineering pipeline produced for one entity as of one
    timestamp, under one feature-set version (see
    app/models/feature_snapshot.py's own docstring). This is what makes
    a past prediction reproducible: a model's `feature_snapshot_id`
    always resolves to precisely what it saw, even after
    `safety_events` changes or feature logic is upgraded.
  * `model_registry_entries` — the minimal model registry (see
    app/models/model_registry_entry.py's own docstring). Tenant-scoped
    by construction: a model is trained on, and only ever serves, one
    organization's own data.
  * `predictions` — one row per prediction attempt, successful or
    abstained (see app/models/prediction.py's own docstring). Full
    provenance via `model_id`/`feature_snapshot_id` foreign keys.

Autogenerated via `alembic revision --autogenerate`, then hand-reviewed:
the same unrelated, pre-existing drift every autogenerate run in this
project detects (a `DROP INDEX`/`CREATE INDEX` pair for
`ix_knowledge_chunk_embeddings_model_identity`, predating this milestone
and every one before it — see migration 0007's own docstring for the
first time this was documented) was again removed from this migration,
which stays purely additive.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('feature_snapshots',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_set_version', sa.String(length=20), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('source_event_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('exposure_basis', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'entity_type', 'entity_id', 'as_of', 'feature_set_version', name='uq_feature_snapshots_entity_as_of_version')
    )
    op.create_index(op.f('ix_feature_snapshots_as_of'), 'feature_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_entity_id'), 'feature_snapshots', ['entity_id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_entity_type'), 'feature_snapshots', ['entity_type'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_organization_id'), 'feature_snapshots', ['organization_id'], unique=False)
    op.create_table('model_registry_entries',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('prediction_target_version', sa.String(length=30), nullable=False),
    sa.Column('label_definition_version', sa.String(length=30), nullable=False),
    sa.Column('feature_set_version', sa.String(length=30), nullable=False),
    sa.Column('training_data_version', sa.String(length=30), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('training_period_start', sa.Date(), nullable=False),
    sa.Column('training_period_end', sa.Date(), nullable=False),
    sa.Column('validation_period_start', sa.Date(), nullable=False),
    sa.Column('validation_period_end', sa.Date(), nullable=False),
    sa.Column('test_period_start', sa.Date(), nullable=False),
    sa.Column('test_period_end', sa.Date(), nullable=False),
    sa.Column('hyperparameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('calibration_validated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'model_name', 'model_version', name='uq_model_registry_name_version')
    )
    op.create_index(op.f('ix_model_registry_entries_model_name'), 'model_registry_entries', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_registry_entries_organization_id'), 'model_registry_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_model_registry_entries_status'), 'model_registry_entries', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('abstention_reason', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=20), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('feature_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_entity_id'), 'predictions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_predictions_entity_type'), 'predictions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_predictions_feature_snapshot_id'), 'predictions', ['feature_snapshot_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_organization_id'), 'predictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_time'), 'predictions', ['prediction_time'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_predictions_prediction_time'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_organization_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_feature_snapshot_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_entity_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_entity_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_registry_entries_status'), table_name='model_registry_entries')
    op.drop_index(op.f('ix_model_registry_entries_organization_id'), table_name='model_registry_entries')
    op.drop_index(op.f('ix_model_registry_entries_model_name'), table_name='model_registry_entries')
    op.drop_table('model_registry_entries')
    op.drop_index(op.f('ix_feature_snapshots_organization_id'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_entity_type'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_entity_id'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_as_of'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    # ### end Alembic commands ###
