"""SIE Milestone 25: Enterprise Risk Assessment Foundation v0.1

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-05

Purely additive: four new tables, all brand-new (via `op.create_table()`,
which auto-creates every native-enum type it references -- safe from
migration 0005's enum-type-creation defect, exactly like migration
0015's own `safety_actions`/`safety_action_history` tables). See
`app/models/risk_assessment.py`'s own docstring for the full entity
relationship and every design decision behind it (versioning/lineage,
candidate-vs-approved-risk separation, system-evidence-vs-human-
assessment column split).

    risk_assessments
        |
        +-- risk_assessment_findings
        |       +-- risk_assessment_controls
        |       +-- risk_assessment_finding_evidence

No existing table's data, columns, or types are touched; migration 0015
is not modified, and `enterprise-risk-v1`
(`app/intelligence/risk_score.py`) is untouched by this migration and by
this entire milestone (item 1's own core architectural rule) -- nothing
here alters the schema that milestone's score reads from.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: Union[str, None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('scope', sa.Enum('ORGANIZATION', 'LOCATION', 'SITE', name='risk_assessment_scope'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'SUPERSEDED', name='risk_assessment_status'), nullable=False),
    sa.Column('lineage_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('assessor_user_id', sa.Uuid(), nullable=True),
    sa.Column('methodology_version', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_api_client_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_api_client_id'], ['api_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_lineage', 'risk_assessments', ['lineage_id'], unique=False)
    op.create_index('ix_risk_assessments_org_site', 'risk_assessments', ['organization_id', 'site_id'], unique=False)
    op.create_index('ix_risk_assessments_org_status', 'risk_assessments', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_risk_assessments_organization_id'), 'risk_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_site_id'), 'risk_assessments', ['site_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_status'), 'risk_assessments', ['status'], unique=False)
    op.create_table('risk_assessment_findings',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('risk_area', sa.Enum('INCIDENT_SAFETY', 'VEHICLE_SAFETY', 'WORKING_AT_HEIGHT', 'PPE_COMPLIANCE', 'ELECTRICAL_SAFETY', 'LIFTING_OPERATIONS', 'ENVIRONMENTAL', 'EQUIPMENT_SAFETY', 'PROCEDURE_VIOLATION', 'FIRE_SAFETY', 'EMERGENCY_PREPAREDNESS', name='risk_area'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_analysis_summary', sa.Text(), nullable=True),
    sa.Column('assessor_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'INSPECTION', 'INTELLIGENCE_RISK_SCORE', 'INTELLIGENCE_ANOMALY', 'INTELLIGENCE_PATTERN', 'INTELLIGENCE_ASSOCIATION', 'INTELLIGENCE_CONCENTRATION', 'INTELLIGENCE_TREND', 'INTELLIGENCE_INDICATOR', 'KNOWLEDGE', name='risk_finding_source'), nullable=False),
    sa.Column('originating_calculation_version', sa.String(length=50), nullable=True),
    sa.Column('occurrence_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ADDRESSED', 'CLOSED', name='risk_finding_status'), nullable=False),
    sa.Column('candidate_status', sa.Enum('IDENTIFIED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='risk_candidate_status'), nullable=True),
    sa.Column('candidate_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('consequence', sa.Integer(), nullable=True),
    sa.Column('inherent_risk_score', sa.Integer(), nullable=True),
    sa.Column('inherent_risk_classification', sa.String(length=20), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_consequence', sa.Integer(), nullable=True),
    sa.Column('residual_risk_score', sa.Integer(), nullable=True),
    sa.Column('residual_risk_classification', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessment_findings_assessment', 'risk_assessment_findings', ['assessment_id'], unique=False)
    op.create_index('ix_risk_assessment_findings_org_risk_area', 'risk_assessment_findings', ['organization_id', 'risk_area'], unique=False)
    op.create_index(op.f('ix_risk_assessment_findings_organization_id'), 'risk_assessment_findings', ['organization_id'], unique=False)
    op.create_table('risk_assessment_controls',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_type', sa.Enum('ELIMINATION', 'SUBSTITUTION', 'ENGINEERING', 'ADMINISTRATIVE', 'PPE', name='risk_control_type'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'IN_PLACE', 'NOT_IMPLEMENTED', name='risk_control_status'), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('effectiveness', sa.Enum('NOT_ASSESSED', 'INEFFECTIVE', 'PARTIALLY_EFFECTIVE', 'EFFECTIVE', name='risk_control_effectiveness'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['risk_assessment_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessment_controls_finding', 'risk_assessment_controls', ['finding_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_controls_organization_id'), 'risk_assessment_controls', ['organization_id'], unique=False)
    op.create_table('risk_assessment_finding_evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.Enum('EVENT', 'ANOMALY', 'PATTERN', 'ASSOCIATION', 'KNOWLEDGE_DOCUMENT', 'ACTION', 'OTHER', name='risk_evidence_type'), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_label', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['risk_assessment_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessment_finding_evidence_finding', 'risk_assessment_finding_evidence', ['finding_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_finding_evidence_organization_id'), 'risk_assessment_finding_evidence', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessment_finding_evidence_organization_id'), table_name='risk_assessment_finding_evidence')
    op.drop_index('ix_risk_assessment_finding_evidence_finding', table_name='risk_assessment_finding_evidence')
    op.drop_table('risk_assessment_finding_evidence')
    op.drop_index(op.f('ix_risk_assessment_controls_organization_id'), table_name='risk_assessment_controls')
    op.drop_index('ix_risk_assessment_controls_finding', table_name='risk_assessment_controls')
    op.drop_table('risk_assessment_controls')
    op.drop_index(op.f('ix_risk_assessment_findings_organization_id'), table_name='risk_assessment_findings')
    op.drop_index('ix_risk_assessment_findings_org_risk_area', table_name='risk_assessment_findings')
    op.drop_index('ix_risk_assessment_findings_assessment', table_name='risk_assessment_findings')
    op.drop_table('risk_assessment_findings')
    op.drop_index(op.f('ix_risk_assessments_status'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_site_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_organization_id'), table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_org_status', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_org_site', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_lineage', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###

    # Native enum types created by the sa.Enum columns above are dropped
    # automatically by op.drop_table() on PostgreSQL only if unused
    # elsewhere; drop them explicitly for a clean downgrade -- exactly
    # migration 0015's own precedent for safety_action_status/priority/type.
    sa.Enum(name='risk_evidence_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_control_effectiveness').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_control_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_control_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_candidate_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_finding_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_finding_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_area').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_assessment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risk_assessment_scope').drop(op.get_bind(), checkfirst=True)
